output:
  output_directory: Documents/gitHub/ainvone/m-und-m/output  # Documents/gitHub/ainvone/m-und-m/output


input: 
  logo_path: data/logo-company.png
  main_image_path: data/pics/foto-haus-main.png
  detail_image_folder: data/pics/detailansicht